# Generated by Django 5.0.1 on 2024-01-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Job_Board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobboard",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
